cart/urls.py
from django.urls import path
from . import views
app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove,name='cart_remove'),
]

shop/urls.py
from django.urls import path
from . import views
app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list,name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail,name='product_detail'),
    path('producto/<int:pk>/favoritos/', views.favoritosview, name='favoritos'),
]

shop/models.py
from django.db import models
from django.urls import reverse
from cuentas.models import User

class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200,unique=True)

    class Meta:
        ordering = ['name']
        indexes = [models.Index(fields=['name']),]
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category,related_name='products',on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    image = models.ImageField(upload_to='products/%Y/%m/%d',blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10,decimal_places=2)
    disponible = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['id', 'slug']),
            models.Index(fields=['name']),
            models.Index(fields=['-created']),
        ]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail',args=[self.id, self.slug])
    
    @property
    def favoritos_total(self):
        return self.favoritos_set.select_related().all().count()

class favoritos(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    producto = models.ForeignKey(Product,on_delete=models.CASCADE)
    creacion = models.DateTimeField(auto_now_add=True)

shop/views.py
from django.shortcuts import render, get_object_or_404,redirect
from .models import Category, Product,favoritos
from cart.forms import CartAddProductForm
from django.contrib.auth.decorators import login_required
from .recommender import Recommender
from orders.models import Order
from django.core.paginator import Paginator


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(disponible=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)

    precio_min = request.GET.get('precio_min')
    precio_max = request.GET.get('precio_max')
    color = request.GET.get('color')
    talla = request.GET.get('talla')

    if precio_min and precio_max:
        products = products.filter(price__gte=precio_min, price__lte=precio_max)
    
    if color:
        products = products.filter(color=color)
    
    if talla:
        products = products.filter(talla=talla)

    paginator = Paginator(products, 2)  # 10 productos por página
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'category': category,
        'categories': categories,
        # 'products': products,
        'products': page_obj,
    }
    return render(request, 'shop/list.html', context)


def product_detail(request, id, slug):
    product = get_object_or_404(Product,id=id,slug=slug,disponible=True)
    cart_product_form = CartAddProductForm()
    r = Recommender()
    recommended_products = r.suggest_products_for([product], 4)
    return render(request,'shop/detail.html',{'product': product,'cart_product_form': cart_product_form,'recommended_products': recommended_products})


@login_required
def favoritosview(request,pk):
    #if request.user.is_authenticated:
    producto = get_object_or_404(Product,pk=pk)
    favorito = favoritos.objects.filter(user=request.user,producto=producto)
    if favorito.exists():#si el usuario ya le dio favorito eliminalo
        favorito[0].delete()
        return redirect('shop:product_list')
    favoritos.objects.create(user=request.user,producto=producto)
    return redirect('shop:product_list')
    #return redirect('cuentas:login')

templates/shop/detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  {{ product.name }}
{% endblock %}
{% block content %}
  <div class="product-detail">
    <img src="{% if product.image %}{{ product.image.url }}{% else %}
    {% static "img/no_image.png" %}{% endif %}">
    <h1>{{ product.name }}</h1>
    <h2>
      <a href="{{ product.category.get_absolute_url }}">
        {{ product.category }}
      </a>
    </h2>
    <p class="price">${{ product.price }}</p>

    <form action="{% url "cart:cart_add" product.id %}" method="post">
      {{ cart_product_form }}
      {% csrf_token %}
      <input type="submit" value="Add to cart">
    </form>

    <form method="post" action="{% url 'shop:favoritos' product.id %}">
      {% csrf_token %}
      <button type="submit" class="btn btn-primary">Agregar a Favoritos</button>
    </form>
    <samp> <i class="fa-regular fa-heart"></i> {{ product.favoritos_total }}</samp>
    
    
    {{ product.description|linebreaks }}
    {% if recommended_products %}
<div class="recommendations">
<h3>People who bought this also bought</h3>
{% for p in recommended_products %}
<div class="item">
<a href="{{ p.get_absolute_url }}">
<img src="{% if p.image %}{{ p.image.url }}{% else %}
{% static "img/no_image.png" %}{% endif %}">
</a>
<p><a href="{{ p.get_absolute_url }}">{{ p.name }}</a></p>
</div>
{% endfor %}
</div>
{% endif %}
  </div>
{% endblock %}

templates/shop/list.html
{% extends "base.html" %}
{% load static %}

{% block title %}
{% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}
<style>
    

</style>

<div id="sidebar">
    <h3>Categories</h3>
    <ul>
        <li {% if not category %}class="selected"{% endif %}>
            <a href="{% url "shop:product_list" %}">All</a>
        </li>
        {% for c in categories %}
        <li {% if category.slug == c.slug %}class="selected"
            {% endif %}>
            <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
        </li>
        {% endfor %}
    </ul>
</div>
<div id="main" class="product-list">
    <h1>{% if category %}{{ category.name }}{% else %}Products{% endif %}</h1>
    {% for product in products %}
    <div class="item">
        <a href="{{ product.get_absolute_url }}">
        <img src="{% if product.image %}{{ product.image.url }}{% else %}{%
        static "img/no_image.png" %}{% endif %}">
        </a>
        <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
        <br>
        ${{ product.price }}
    </div>
    {% endfor %}
</div>

<!-- Mostrar enlaces de paginación -->
<br>
<div class="pagination">
  <span class="step-links">
    {% if products.has_previous %}
      <a href="?page=1">&laquo; Primera</a>
      <a href="?page={{ products.previous_page_number }}">Anterior</a>
    {% endif %}

    <span class="current">
      Página {{ products.number }} de {{ products.paginator.num_pages }}.
    </span>

    {% if products.has_next %}
      <a href="?page={{ products.next_page_number }}">Siguiente</a>
      <a href="?page={{ products.paginator.num_pages }}">Última &raquo;</a>
    {% endif %}
  </span>
</div>
<br>


<form method="GET">
    <label for="precio_min">Precio mínimo:</label>
    <input type="number" name="precio_min" id="precio_min">
    
    <label for="precio_max">Precio máximo:</label>
    <input type="number" name="precio_max" id="precio_max">
  
    <label for="color">Color:</label>
    <select name="color" id="color">
      <option value="">Todos</option>
      <option value="rojo">Rojo</option>
      <option value="azul">Azul</option>
      <option value="verde">Verde</option>
    </select>
  
    <label for="talla">Talla:</label>
    <select name="talla" id="talla">
      <option value="">Todas</option>
      <option value="s">S</option>
      <option value="m">M</option>
      <option value="l">L</option>
    </select>
  
    <button type="submit">Filtrar</button>
  </form>
  

<script src="{% static 'js/hola.js' %}"></script>
{% endblock %}