cart/urls.py
from django.urls import path
from . import views
app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove,name='cart_remove'),
]

cuentas/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import registro,editarperfil

app_name = 'cuentas'
urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('registro/',registro,name='registro'),
    path('editarperfil/',editarperfil,name='editarperfil'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<title>{% block title %}My shop{% endblock %}</title>
{% comment %} <link rel="stylesheet" href="{% static 'css/hola.css' %}"> {% endcomment %}
<link rel="stylesheet" href="{% static 'css/hola.css' %}">
<link href="{% static "css/base.css" %}" rel="stylesheet">
<script src="https://kit.fontawesome.com/6ab59aed01.js" crossorigin="anonymous"></script>
</head>
<body>
<div id="header">
<a href="/" class="logo">My shop</a>
</div>
<div id="subheader">

<div class="cart">
    {% if user.is_authenticated %}
    {{ user.username}}
    <a href="{% url 'cuentas:logout' %}">Logout</a>
    <a href="{% url 'cuentas:editarperfil' %}">editar perfil papu</a>
    {% else %}
    <a href="{% url 'cuentas:login' %}">login</a>
    <a href="{% url "social:begin" "google-oauth2" %}">Google+</a>
    <a href="{% url 'cuentas:registro' %}">registrarse</a>
    {% endif %}

    {% with total_items=cart|length %}
    {% if total_items > 0 %}
    Your cart:
    <a href="{% url "cart:cart_detail" %}">
    {{ total_items }} item{{ total_items|pluralize }},
    ${{ cart.get_total_price }}
    </a>
    {% else %}
    Your cart is empty.
    {% endif %}
    {% endwith %}
</div>
</div>
<div id="content">
{% block content %}
{% endblock %}
</div>
</body>
</html>